version: "3.3"

services:
  nginx:
    image: nginx
    ports:
      - 8080:80
    volumes:
      - ./public:/usr/share/nginx/html
      - ./nginx/config/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/log:/var/log/nginx

  fluentd:
    build: ./fluentd
    volumes:
      - ./fluentd/fluentd.conf:/fluentd/etc/fluentd.conf:ro
      - ./nginx/log:/var/log/nginx
    ports:
      - 24224:24224
    environment:
      FLUENTD_CONF: fluentd.conf
    depends_on:
      - elasticsearch

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.5.4
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - 9200:9200
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.5.4
    container_name: kibana
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch

volumes:
  esdata:
    driver: local
